[tools]
python = "latest"
zig = "latest"
bun = "latest"

[env]
# AWS ECR registry
ECR_REGISTRY = "912951144733.dkr.ecr.us-west-2.amazonaws.com"

[tasks]
build = 'pnpm --filter "./js-apps/*" build'
clean = 'pnpm --filter "./js-apps/*" clean'
dev = 'pnpm --filter "./js-apps/*" dev'
format = 'prettier --write "**/*.{ts,tsx,md}"'
lint = 'pnpm --filter "./js-apps/*" lint'
test = 'pnpm --filter "./js-apps/*" test'
