
---
- name: Security Hardening
  hosts: all
  gather_facts: yes
  
  pre_tasks:
    # 安装 fail2ban 依赖包
    - name: Install fail2ban dependencies
      package:
        name:
          - python3-systemd
          - iptables
          - ipset
        state: present
      when: security_fail2ban_enabled | default(true)
      tags: [security, fail2ban, packages]
  
  roles:
    - role: willshersystems.sshd
      tags: [ssh]
    
    - role: geerlingguy.security
      tags: [security]
    
    - role: geerlingguy.firewall
      tags: [firewall]
  
  post_tasks:
    - name: Verify security services
      include_tasks: ../tasks/verify-services.yml
      tags: [verify]
